name: unit_testing

on:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'build new code into test environment and run tests'
        run:  docker container run -v $PWD:/AutoQC_latest iquod/autoqc:1.0-rc6 bash -c "cp /AutoQC/data/* /AutoQC_latest/data/.; cd /AutoQC_latest; /usr/local/bin/nosetests tests/*.py"


